ministryofjustice/hmpps-strengths-based-needs-assessments-ui

- app/common/controllers/saveAndContinue.ts
- app/common/controllers/saveAndContinue.utils.test.ts
- app/common/controllers/saveAndContinue.utils.ts
- app/sbna-poc/v1_0__initial-form/fields.ts
- app/sbna-poc/v1_0__initial-form/steps.ts
- server/@types/hmpo-form-wizard/index.d.ts
We have our date fields split accross three inputs in the UI so need to combine them before validation etc..
> Add processing of date fields

- app/common/controllers/saveAndContinue.utils.ts
- app/oastub/v1_0__initial-form/controllers/startController.ts
- app/sbna-poc/v1_0__initial-form/controllers/saveAndContinueController.ts
- app/sbna-poc/v1_0__initial-form/fields.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/services/strengthsBasedNeedsService.ts
- server/views/components/question/template.njk
- wiremock/mocks/strengthsBasedNeedsApi.ts
- Update SBNA API service
- Update Wiremock
- Add integration to SaveAndContinueController
> Add answer endpoint integration

- server/views/forms/layout.njk
Move the summary to better fit with the new dynamic header sizing
> Move error summary component

- app/sbna-poc/v1_0__initial-form/fields/employment-education.ts
- assets/scss/components/_form-fields.scss
- assets/scss/components/_summary.scss
- server/views/components/analysis/template.njk
- server/views/components/question/template.njk
- server/views/components/summary/accommodation/template.njk
- server/views/components/summary/alcohol/template.njk
- server/views/components/summary/drugs/template.njk
- server/views/components/summary/employment-education/template.njk
- server/views/components/summary/finance/template.njk
- Update font sizing on analysis screen
- Add larger margin between questions
- Add css classes for summary and analysis components
> Update form styles

- server/views/forms/layout.njk
Just a temporary fix to allow the user to reset their journey during UR
> Update close assessment button to take user back to OAStub

- app/sbna-poc/v1_0__initial-form/fields/common.ts
- app/sbna-poc/v1_0__initial-form/fields/employment-education.ts
- app/sbna-poc/v1_0__initial-form/fields/health-wellbeing.ts
- app/sbna-poc/v1_0__initial-form/fields/index.ts
- app/sbna-poc/v1_0__initial-form/steps/health-wellbeing.ts
- app/sbna-poc/v1_0__initial-form/steps/index.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/views/forms/sbna-poc/health-wellbeing-summary-analysis-complete.njk
- server/views/forms/sbna-poc/health-wellbeing-summary-analysis.njk
- Create initial health and wellbeing pages
- Add health and wellbeing fields
> Add health and well being fields

- .circleci/config.yml
- helm_deploy/values-test.yaml
additionally:
- use latest version of HMPPS Orb
- fixes Deployment integration with Jira
- adds Build integration with Jira
> ARN-1817 Ability to trigger manual deploys to the new test environment

- app/oastub/v1_0__initial-form/controllers/createOneTimeLinkController.ts
- app/oastub/v1_0__initial-form/controllers/oneTimeLinkStartController.ts
- app/oastub/v1_0__initial-form/fields.ts
- app/oastub/v1_0__initial-form/steps.ts
- server/views/forms/oastub/otl-create.njk
- server/views/forms/oastub/otl.njk
This should allow us to step back in to an existing assessment with OAStub, useful for user-testing and testing assessment versioning etc..
> Update OAStub to allow assessment ID to be specified

- app/sbna-poc/v1_0__initial-form/fields/employment-education.ts
- Update option text
- Update stylings for labels
> ARN-2065 Update responses for EF1

- app/sbna-poc/v1_0__initial-form/fields/employment-education.ts
- app/sbna-poc/v1_0__initial-form/steps/employment-education.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/utils/nunjucks.summaryFields.ts
- Update routng logic to be explicit
- Update ordering of educaton questions to match design
> ARN-2067 - Update routing logic for education and employment

- app/sbna-poc/v1_0__initial-form/fields/accommodation.ts
- app/sbna-poc/v1_0__initial-form/fields/common.test.ts
- app/sbna-poc/v1_0__initial-form/fields/common.ts
re-opened because additional changes weren't showing on the original PR
> ARN-2061 remove required validaton from temp accomm end dates

- app/common/utils/forms/formRouterBuilder.ts
- app/sbna-poc/v1_0__initial-form/fields/personal-relationships-community.ts
- Add missing fields to FormWizard config
- Add code to check fields/steps configuration integrity
> ARN-2119 - Fix bug causing PR&C to lose data

- server/views/components/summary/thinking-behaviours-attitudes/template.njk
> rendering PoPs name on warning text in TBA summary screen

- server/views/components/summary/health-wellbeing/template.njk
- Update summary to only display psych treatment answers when subject has mental health condition
> ARN-2122 - Update health and wellbeing summary

- app/sbna-poc/v1_0__initial-form/steps/accommodation.ts
- cypress/e2e/v1.0/accommodation/journeys/user-journey.cy.ts
- cypress/e2e/v1.0/accommodation/steps/accommodation.ts
- cypress/support/commands/option.ts
- cypress/support/index.ts
- Fix bug in Accommodation routing logic
> ARN-1897 - Add user journey Cypress tests for Accommodation section

- app/common/utils/forms/formRouterBuilder.test.ts
- app/sbna-poc/v1_0__initial-form/controllers/saveAndContinueController.test.ts
- app/sbna-poc/v1_0__initial-form/controllers/saveAndContinueController.ts
- app/sbna-poc/v1_0__initial-form/fields/index.ts
- app/sbna-poc/v1_0__initial-form/steps/accommodation.ts
- app/sbna-poc/v1_0__initial-form/steps/alcohol.ts
- app/sbna-poc/v1_0__initial-form/steps/common.test.ts
- app/sbna-poc/v1_0__initial-form/steps/common.ts
- app/sbna-poc/v1_0__initial-form/steps/drugs.ts
- app/sbna-poc/v1_0__initial-form/steps/employment-education.ts
- app/sbna-poc/v1_0__initial-form/steps/finance.ts
- app/sbna-poc/v1_0__initial-form/steps/health-wellbeing.ts
- app/sbna-poc/v1_0__initial-form/steps/index.ts
- app/sbna-poc/v1_0__initial-form/steps/personal-relationships-community.ts
- app/sbna-poc/v1_0__initial-form/steps/thinking-behaviour-attitudes.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/utils/nunjucks.summaryFields.ts
- server/utils/nunjucks.utils.test.ts
- server/utils/nunjucks.utils.ts
- server/utils/nunjucksSetup.ts
- server/views/forms/default.njk
- server/views/forms/layout.njk
- server/views/forms/sbna-poc/alcohol-summary-analysis.njk
- server/views/forms/sbna-poc/drugs-summary-analysis.njk
- server/views/forms/sbna-poc/finance-summary-analysis.njk
- server/views/forms/sbna-poc/health-wellbeing-summary-analysis.njk
- server/views/forms/sbna-poc/summary-analysis-incomplete.njk
- server/views/forms/sbna-poc/thinking-behaviours-attitudes-summary-analysis.njk
- Add field for assessment complete to all steps
- Refactor section completion code
> ARN-2148 - Add assessment complete field

- app/form/v1_0/steps/accommodation.ts
- cypress/e2e/v1.0/journeys/accommodation.cy.ts
- cypress/e2e/v1.0/pages/accommodation/temporary-accommodation-2.cy.ts
- AC02 route now displays suitable housing location question (AC13)
> ARN-2299 - Update accommodation steps

- app/form/v1_0/fields/health-wellbeing.ts
- app/form/v1_0/fields/thinking-behaviours-attitudes.ts
- cypress/e2e/v1.0/fixtures/complete-assessment.fixture.ts
- cypress/e2e/v1.0/journeys/health-wellbeing.cy.ts
- cypress/e2e/v1.0/pages/health-wellbeing/practitioner-analysis.cy.ts
- cypress/e2e/v1.0/pages/health-wellbeing/questions/optimisticAboutFuture.ts
- cypress/e2e/v1.0/pages/thinking-behaviours-attitudes/questions/stable-behaviour.ts
- cypress/e2e/v1.0/print-preview.cy.ts
Contains tickets ARN-2376 + ARN-2373 combined
> Arn 2376 ready for dev refinement add body text to question tb 02

- app/form/v1_0/fields/health-wellbeing.ts
- cypress/e2e/v1.0/pages/health-wellbeing/questions/physicalHealthCondition.ts
Reverts ministryofjustice/hmpps-strengths-based-needs-assessments-ui#758
> Revert "Arn 2509 dev update response radio button multiple sections"

- app/form/v1_0/fields/common/fieldsFactory.ts
- app/form/v1_0/fields/health-wellbeing.ts
- cypress/e2e/v1.0/pages/accommodation/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/alcohol-use/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/drug-use/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/employment-education/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/finance/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/health-wellbeing/questions/optimisticAboutFuture.ts
- cypress/e2e/v1.0/pages/health-wellbeing/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/personal-relationships-community/questions/wantToMakeChanges.ts
- cypress/e2e/v1.0/pages/thinking-behaviours-attitudes/questions/wantToMakeChanges.ts
> ARN-2557: Update hint text

- .husky/pre-push
New team working on this code means we'll probably make some mistakes; let's try and pick those up early.
> Adds linting and runs unit tests when pushing code

- app/form/v1_0/fields/drug-use/drug-use-history.ts
- app/form/v1_0/fields/drug-use/index.ts
First pass at setting up fields for Drug Use History
> ARN-2702 drug use history

- app/form/v1_0/fields/drug-use/drug-use-history.ts
Fixes a hint, removes some superfluous field dependencies and fix the subject name replacement in a few places where it had been copy/pasted in from the figma screenshots.
> ARN-2702 text fixes

- app/form/v1_0/fields/common/utils.ts
- app/form/v1_0/fields/offence-analysis.ts
- app/form/v1_0/fields/personal-relationships-community.ts
- app/form/v1_0/fields/thinking-behaviours-attitudes.ts
- app/form/v1_0/steps/drug-use.ts
- server/@types/hmpo-form-wizard/index.d.ts
- server/views/forms/default.njk
- server/views/forms/layout.njk
Had a convo with Cal, questions with the heading "Drug use background" Should not be nested where as questions for "Practitioner Analysis"/"Summary" etc should be. Added two new fields as to not make changes for our other sections.
> Add headers to new drugs section

- app/controllers/saveAndContinueController.ts
I'm too stupid to understand the original code, sorry.
> Small legibility refactoring

- app/form/v1_0/fields/drug-use/drug-use-history.ts
Missing word discovered during design review.
> ARN-2702 adds missing and

- app/form/v1_0/fields/offence-analysis.ts
- cypress/e2e/v1.0/pages/offence-analysis/questions/elementsOfTheOffence.ts
- cypress/support/commands/question.ts
Added 'or' divider to the page for one question, before the last checkbox: None
> ARN-2829 Adding 'Or' text and logic to OA question

- app/form/v1_0/fields/common/fieldsFactory.ts
- cypress/e2e/v1.0/common/practitioner-analysis/questions/linkedToRiskOfReoffending.ts
- cypress/e2e/v1.0/common/practitioner-analysis/questions/linkedToRiskOfSeriousHarm.ts
- cypress/e2e/v1.0/common/practitioner-analysis/questions/strengthsOrProtectiveFactors.ts
> ARN 2840 - Practitioner Analysis questions - review error messages for all sections

- cypress/e2e/v1.0/journeys/drug-use.cy.ts
This adds the remaining journeys tests to the Drug Use section, including the conditional questions for injectables.
> ARN-2852 Add injectable journey tests

- app/form/v1_0/fields/drug-use/drug-details.ts
- cypress/e2e/v1.0/pages/drug-use/questions/drugUsedInTheLastSixMonths.ts
> ARN-2863 Corrects drug frequency error message

- app/form/v1_0/fields/drug-use/drugs.ts
- cypress/e2e/v1.0/pages/drug-use/common/drugs.ts
Changes "hallucinogenics (including ketamine)" to "hallucinogens".
> ARN-2859 Hallucinogenics content change

- app/form/v1_0/fields/personal-relationships-community.ts
- cypress/e2e/v1.0/pages/personal-relationships-community/questions/childrenInformation.ts
> ARN-2805 Prevents users from selecting that both do and do not have children in their life.

- cypress/support/commands/page.ts
- server/views/forms/layout.njk
Add visually hidden text for section complete status, for screen readers
> ARN-2797 Accessibility - Side Nav Component Completion Status

- server/views/partials/offenderDetails.njk
> ARN 2907 Relocate Back Link
